version: '3.8'
services:
    php-apache-environment:
        container_name: apk-manager-php
        build:
            context: ./php-apache2
            dockerfile: Dockerfile
        volumes:
            - ./sources/:/var/www/html/
        ports:
            - 8000:80
